### PR TITLE
Fix sudden CI errors

### PR DESCRIPTION
**Pull request by Arlodotexe**
This PR
- Fixes several errors related to missing XMLDoc comments.
- Updates our uno.check version to the latest 1.27.4
- Attempts unblock our CI

Prerequisite PR https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/249

### CODE REVIEW

**Comment by michael-hawker** [comment]
Hmm, looks like Uno-check isn't it...

> "/home/runner/work/Windows/Windows/tooling/ProjectHeads/AllComponents/Wasm/CommunityToolkit.App.Wasm.csproj" (default target) (1:10) ->
       (UnoGenerateAssetsManifest target) -> 
         /home/runner/.nuget/packages/uno.wasm.bootstrap/9.0.8/build/Uno.Wasm.Bootstrap.targets(270,3): error MSB4044: The "GenerateUnoAssetsManifest_v05da712db32bc85a0fb32e039ff4b1d24a10ddbb" task was not given a value for the required parameter "OutputPackagePath". [/home/runner/work/Windows/Windows/tooling/ProjectHeads/AllComponents/Wasm/CommunityToolkit.App.Wasm.csproj::TargetFramework=net9.0]

@JeromeLaban did something else change this year we should be aware of?

This build on main passed at the end of 2024: https://github.com/CommunityToolkit/Windows/actions/runs/12550855416

And our next one with a simple typo fixed failed (and subsequent are failing): https://github.com/CommunityToolkit/Windows/actions/runs/12934722557

**Comment by jeromelaban** [comment]
> @jeromelaban did something else change this year we should be aware of?

Yes, there is, it's a breaking changes for wasm in .NET 9.0.102 that we fixed with the uno.wasm.bootstrap [9.0.10](https://www.nuget.org/packages/Uno.Wasm.Bootstrap/9.0.10), there's also a workaround in https://github.com/unoplatform/uno/issues/19232#issuecomment-2593350508 if you cannot update yet.

**Comment by michael-hawker** [comment]
Thanks Jerome! FYI @Arlodotexe - We should just be able to update the bootstrapper, eh? As we've moved to .NET 9?

**Comment by Arlodotexe** [comment]
Huge thanks @jeromelaban, I'll give that a go!

> Thanks Jerome! FYI @Arlodotexe - We should just be able to update the bootstrapper, eh? As we've moved to .NET 9?

Notice how the other platforms are now failing after updating tooling. There are various "missing xml comment" error-warnings to resolve now, at least a dozen or two. Got that done locally, will push soon!

File: components/Primitives/src/SwitchPresenter/SwitchConverter.cs [hunk 1]
```diff
@@ -66,13 +66,19 @@ public SwitchConverter()
         SwitchCases = new CaseCollection();
     }
 
+    /// <summary>
+    /// Converts the provided value based on the defined cases.
+    /// </summary>
```
Comment (michael-hawker) [inline components/Primitives/src/SwitchPresenter/SwitchConverter.cs:71]: Could this be inheritdoc tag as it's from the IValueConverter interface? (same with below?)

File: components/Segmented/src/Segmented/Segmented.cs
Comment (michael-hawker) [inline components/Segmented/src/Segmented/Segmented.cs:1]: Can the overrides be inheritdoc here too?

**Review by michael-hawker — APPROVED** [review]
Think we can use inheritdoc in a few more places, but LGTM. Approving so we'll be unblocked once we get a clean CI and merge the submodule in before. Thanks!

**Comment by michael-hawker** [comment]
Looks like still have some XML clean-up. Not sure how we weren't catching that before. We've had that check on in the past.

**Comment by Arlodotexe** [comment]
The error that's appearing on UWP:
```
       "V:\Windows\tooling\ProjectHeads\AllComponents\uwp\CommunityToolkit.App.Uwp.csproj" (Clean;Build target) (1:7) ->
       "V:\Windows\components\SettingsControls\samples\SettingsControls.Samples.csproj" (default target) (5:25) ->
       "V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj" (default target) (7:32) ->
       (CoreCompile target) ->
         V:\Windows\components\Extensions\src\ListViewBase\ListViewExtensions.Command.cs(20,29): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also m 
       atched other overloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ListViewBase\ListViewExtensions.Command.cs(22,91): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also m 
       atched other overloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ListViewBase\ListViewExtensions.Command.cs(23,33): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also m 
       atched other overloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ListViewBase\ListViewExtensions.Command.cs(30,29): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also m 
       atched other overloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ListViewBase\ListViewExtensions.Command.cs(32,86): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also m 
       atched other overloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ListViewBase\ListViewExtensions.Command.cs(33,44): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also m 
       atched other overloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\Markup\BitmapIconExtension.cs(14,37): error CS0419: Ambiguous reference in cref attribute: 'Uri'. Assuming 'Uri', but could have also matched other overloads  
       including 'Uri'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\Markup\BitmapIconSourceExtension.cs(14,37): error CS0419: Ambiguous reference in cref attribute: 'Uri'. Assuming 'Uri', but could have also matched other over 
       loads including 'Uri'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(13,76): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(18,76): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(23,29): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(25,95): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(26,33): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(33,29): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(35,90): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(36,44): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(43,29): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(45,95): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(46,33): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(53,29): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(55,90): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\ScrollViewer\ScrollViewerExtensions.Properties.cs(56,44): error CS0419: Ambiguous reference in cref attribute: 'Thickness'. Assuming 'Thickness', but could ha 
       ve also matched other overloads including 'Thickness'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\Text\HyperlinkExtensions.cs(19,31): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also matched other ov 
       erloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\Text\HyperlinkExtensions.cs(24,77): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also matched other ov
       erloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\Text\HyperlinkExtensions.cs(34,29): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also matched other ov 
       erloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\Text\HyperlinkExtensions.cs(36,99): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also matched other ov 
       erloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\Text\HyperlinkExtensions.cs(37,33): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also matched other ov 
       erloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\Text\HyperlinkExtensions.cs(41,29): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also matched other ov 
       erloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\Text\HyperlinkExtensions.cs(43,84): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also matched other ov 
       erloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
         V:\Windows\components\Extensions\src\Text\HyperlinkExtensions.cs(44,44): error CS0419: Ambiguous reference in cref attribute: 'ICommand'. Assuming 'ICommand', but could have also matched other ov 
       erloads including 'ICommand'. [V:\Windows\components\Extensions\src\CommunityToolkit.WinUI.Extensions.csproj::TargetFramework=uap10.0.17763]
```

**Comment by Arlodotexe** [comment]
Possibly related: https://github.com/dotnet/roslyn/issues/51013

**Comment by Arlodotexe** [comment]
@michael-hawker We're thinking this may be caused by https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/245

Since this is clearly a platform bug, we'll suppress this for now.
