### ISSUE TITLE
Cant compile with Uno 5.1 and CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.0.240109"

### ISSUE THREAD

**Issue by cconner100** [CommunityToolkit/Windows#341]
### Describe the bug

Trying to use the SettingsControl in a uno 5.1 project and i get the following error when compiling

E:\ZiiDMS\ZiiDMSApp\Client\ZiiDMSApp\ZiiDMSApp.Mobile\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.BindableTypeProvi
ders.BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(3674,91): error CS0433: The type 'CameraHelper' exists
in both 'CommunityToolkit.WinUI.Helpers, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null' and 'CommunityToolkit.W
inUI, Version=7.1.0.0, Culture=neutral, PublicKeyToken=4aff67a105548ee2' [E:\ZiiDMS\ZiiDMSApp\Client\ZiiDMSApp\ZiiDMSAp
p.Mobile\ZiiDMSApp.Mobile.csproj::TargetFramework=net8.0-android]

I am using the following nugets

    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageVersion Include="CommunityToolkit.WinUI" Version="7.1.2" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.0.240109" />
    <PackageVersion Include="CommunityToolkit.WinUI.UI" Version="7.1.2" />
    <PackageVersion Include="CommunityToolkit.WinUI.UI.Animations" Version="7.1.2" />
    <PackageVersion Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />

    <PackageVersion Include="Uno.CommunityToolkit.WinUI" Version="7.1.200" />
    <PackageVersion Include="Uno.CommunityToolkit.WinUI.UI" Version="7.1.200" />
    <PackageVersion Include="Uno.CommunityToolkit.WinUI.UI.Animations" Version="7.1.200" />
    <PackageVersion Include="Uno.CommunityToolkit.WinUI.UI.Controls" Version="7.1.200" />

### Steps to reproduce

```text
Add a simple screen in the Uno sample project, Include the SettingsControl.
```

### Expected behavior

Should be able to compile and run in Windows, iOS and Android

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [X] Android
- [X] iOS
- [X] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [X] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [X] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Visual Studio Version

2022, Preview

### Device form factor

Desktop, Mobile

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by lukasf** [comment]
You are using both CommunityToolkit 7 and 8 in parallel. You cannot do that. If you want to update to 8.x, you must remove all 7.x packages and add 8.x ones.

But SettingsControl does not yet work on Android or iOS with CommunityTookit 8.x, it crashes with MissingMethodException. So you need to wait until that is fixed. I hope it will be fixed in 8.1.

**Comment by Arlodotexe** [comment]
> You are using both CommunityToolkit 7 and 8 in parallel. You cannot do that. If you want to update to 8.x, you must remove all 7.x packages and add 8.x ones.

This is correct. Further, there's been many under-the-hood fixes from Uno in the latest version 8.2+ that we recommend using instead of 8.0 or 8.1.

**Comment by cconner100** [comment]
ok but there are control conflicts that are now not working, in 8.x there is now no markdown control its only available in 7.x which is why i am in this situation.

Uno really needs a markdown control that works
